DEBUG:root:Order:2 9 85.0
DEBUG:root:Finish turn

ERROR:root:Error in bot.
Traceback (most recent call last):
  File "opponent_bots/production_bot.py", line 46, in <module>
    current_line = input()
EOFError: EOF when reading a line
